//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginsDB.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_login
    {
        public int master_id { get; set; }
        public string m_username { get; set; }
        public string m_password { get; set; }
        public string reset_key { get; set; }
        public string email { get; set; }
    }
}
